import type { Metadata } from 'next';
import { IBM_Plex_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/Header';

const ibm = IBM_Plex_Mono({
  display: 'swap',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Project_001',
  description: 'Generated by create next app',

  icons: {
    icon: '/favicon_v2.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          ibm.className,
          'antialiased',
          'flex',
          'flex-col',
          'min-h-screen'
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="flex justify-center w-full h-full mx-auto p-4 max-w-[1200px] flex-1">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
